Javadoc exclusion
fedora-java/xmvn pull request #176
Opened 2022-03-25 08:52 UTC by mkoncek

Currently the integration test fails with:
```
[ERROR] javadoc: error - File not found: "xcludePackageNames/src/main/java/b/z/Main.java"
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 31.526 s <<< FAILURE! - in org.fedoraproject.xmvn.it.maven.mojo.javadoc.JavadocExcludePackageNamesTest
[ERROR] org.fedoraproject.xmvn.it.maven.mojo.javadoc.JavadocExcludePackageNamesTest.testJavadocExcludePackageNames  Time elapsed: 31.167 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>
        at org.fedoraproject.xmvn.it.maven.mojo.javadoc.JavadocExcludePackageNamesTest.testJavadocExcludePackageNames(JavadocExcludePackageNamesTest.java:39)
```

2022-03-25 10:08 UTC, mizdebsk requested changes

2022-03-25 10:08 UTC, mizdebsk commented on xmvn-mojo/src/main/java/org/fedoraproject/xmvn/mojo/JavadocMojo.java
> +    private List<String> compileSourceRoots;
This won't work. This is an aggregator MOJO, which means it is ran for all reactor projects. You need to iterate over all reactor projects and get compile source roots of each of them.

2022-03-25 10:08 UTC, mizdebsk commented on xmvn-mojo/src/main/java/org/fedoraproject/xmvn/mojo/JavadocMojo.java
> +                    return Paths.get( sourceRoot ).relativize( sourceFile ).toString().matches( excludePackagesRegex );
1. You should return true only if there is a match, otherwise continue looping. Return false after all source roots were processed and none matched.
2. Regex is compiled in each loop iteration. Regex compilation should be moved outsides of the loop.

2022-03-25 10:08 UTC, mizdebsk commented on xmvn-mojo/src/main/java/org/fedoraproject/xmvn/mojo/JavadocMojo.java
> +    private void doExcludePackagesRegex( Set<Path> sourceFiles )
Why not implement path filtering in findFiles method? Why a separate method is added?

2022-03-28 11:34 UTC, mkoncek commented
I completely reworked the code but all the issues should be addressed.

2022-06-23 06:18 UTC, mizdebsk commented
Sorry, I missed the update.
Looks good now.
@mkoncek Can you please resolve merge conflict?

2022-06-24 07:04 UTC, mkoncek commented
Done.

2022-06-24 08:07 UTC, mkoncek commented
I think the current maven-checkstyle is too restrictive and would have to be edited every year.

2022-06-24 11:32 UTC, fridrich commented
Would something like this make it work again:

--- a/aux/license-header.txt
+++ b/aux/license-header.txt
@@ -1,5 +1,5 @@
 ^/\*-$
-^ \* Copyright \(c\) (20(1[2-9]|2[0-0])-)?2021 Red Hat, Inc\.$
+^ \* Copyright \(c\) (20(1[2-9]|2[0-1])-)?2022 Red Hat, Inc\.$
 ^ \*$
 ^ \* Licensed under the Apache License, Version 2\.0 \(the "License"\);$
 ^ \* you may not use this file except in compliance with the License\.$

?

2022-07-21 08:33 UTC, mkoncek commented
This PR is not ready to be merged. First we need to make sure it solves the original problem: building mariadb-java-client, but there are different problems.

2023-09-19 05:12 UTC, closed without merging

2023-09-19 05:12 UTC, mizdebsk commented
Closing due to inactivity. Feel free to reopen once the code is ready to be reviewed.